DROP DATABASE IF EXISTS `forum`;
CREATE DATABASE `forum` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; 

SET sql_mode="";
USE `forum`;

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '用户名',
    `nickname` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '昵称',
    `password` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '密码hash',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态',
    `createdtime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
    `updatedtime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '修改时间',
    PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT='用户表';

DROP TABLE IF EXISTS `post`;
CREATE TABLE IF NOT EXISTS `post`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
    `title` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '标题',
    `content` TEXT DEFAULT '' COMMENT '内容',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态',
    `createdtime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
    `updatedtime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '修改时间',
    PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT='帖子表';
